services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:80"
    depends_on:
      - pgdb

  pgdb:
    image: bitnami/postgresql
    environment:
      - POSTGRES_DB=Warehouse_4
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Tim597707
    container_name: pgdb
    ports:
      - "5432:5432"

    volumes:
      - pgdb:/var/lib/postgresql/data/

volumes:
  pgdb: {}
