# Generated by Django 5.0.6 on 2024-09-14 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title*')),
                ('content', models.TextField(max_length=1000, verbose_name='Text*')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Image (Best: 800x600)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
