# Generated by Django 5.0.6 on 2024-09-20 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScan_deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QRScan_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcodes.qrscan')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse_stock_deploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse_stock_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcodes.warehouse_stock')),
            ],
        ),
    ]
