# Generated by Django 5.0.6 on 2024-09-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_qrscan_deploy_warehouse_stock_deploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse_stock_deploy',
            name='Warehouse_stock_dep',
        ),
        migrations.DeleteModel(
            name='QRScan_deploy',
        ),
        migrations.DeleteModel(
            name='Warehouse_stock_deploy',
        ),
    ]
