# Generated by Django 5.1.2 on 2025-03-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_content_alter_news_image_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
