# Generated by Django 5.1.2 on 2025-01-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='item',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
