# Generated by Django 5.1.2 on 2025-03-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0002_remove_item_qr_code_item_qr_code_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscan',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrscan',
            name='invoice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
