# Generated by Django 5.1.2 on 2025-03-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodes', '0003_qrscan_invoice_id_qrscan_invoice_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrscan',
            name='invoice_photo',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
